In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
import matplotlib.pyplot as plt

First,We have to import dataset from the internet

In [ ]:
data=pd.read_csv("ecommerce_customer_data_custom_ratios.csv")

Head() is used for display the table

In [ ]:
data.head()

,Customer ID,Purchase Date,Product Category,Product Price,Quantity,Total Purchase Amount,Payment Method,Customer Age,Returns,Customer Name,Age,Gender,Churn
0,46251,2020-09-08 09:38:32,Electronics,12,3,740,Credit Card,37,0.0,Christine Hernandez,37,Male,0
1,46251,2022-03-05 12:56:35,Home,468,4,2739,PayPal,37,0.0,Christine Hernandez,37,Male,0
2,46251,2022-05-23 18:18:01,Home,288,2,3196,PayPal,37,0.0,Christine Hernandez,37,Male,0
3,46251,2020-11-12 13:13:29,Clothing,196,1,3509,PayPal,37,0.0,Christine Hernandez,37,Male,0
4,13593,2020-11-27 17:55:11,Home,449,1,3452,Credit Card,49,0.0,James Grant,49,Female,1

In [ ]:
data.head(5)

,Customer ID,Purchase Date,Product Category,Product Price,Quantity,Total Purchase Amount,Payment Method,Customer Age,Returns,Customer Name,Age,Gender,Churn
0,46251,2020-09-08 09:38:32,Electronics,12,3,740,Credit Card,37,0.0,Christine Hernandez,37,Male,0
1,46251,2022-03-05 12:56:35,Home,468,4,2739,PayPal,37,0.0,Christine Hernandez,37,Male,0
2,46251,2022-05-23 18:18:01,Home,288,2,3196,PayPal,37,0.0,Christine Hernandez,37,Male,0
3,46251,2020-11-12 13:13:29,Clothing,196,1,3509,PayPal,37,0.0,Christine Hernandez,37,Male,0
4,13593,2020-11-27 17:55:11,Home,449,1,3452,Credit Card,49,0.0,James Grant,49,Female,1

we have perfrom the removing duplicates in given dataset

In [ ]:
data.drop_duplicates(inplace=True)

In [ ]:
data.dropna(inplace=True)

In [ ]:
data.head(2)

,Customer ID,Purchase Date,Product Category,Product Price,Quantity,Total Purchase Amount,Payment Method,Customer Age,Returns,Customer Name,Age,Gender,Churn
0,46251,2020-09-08 09:38:32,Electronics,12,3,740,Credit Card,37,0.0,Christine Hernandez,37,Male,0
1,46251,2022-03-05 12:56:35,Home,468,4,2739,PayPal,37,0.0,Christine Hernandez,37,Male,0

which is an the raw data contain noisy data so,by using the conversion Convert date format

In [ ]:
data['Purchase Date']=pd.to_datetime(data['Purchase Date'])

EDA-Exploratary data analysis

1.describe()-it is used for calculate the data like mean,mode,min,max...

In [ ]:
data.describe()

,Customer ID,Purchase Date,Product Price,Quantity,Total Purchase Amount,Customer Age,Returns,Age,Churn
count,202404.000000,202404,202404.000000,202404.000000,202404.000000,202404.000000,202404.000000,202404.000000,202404.000000
mean,25013.981962,2021-11-07 01:49:42.200015360,254.377423,2.999269,2725.130813,43.926498,0.497861,43.926498,0.199423
min,1.000000,2020-01-01 00:15:00,10.000000,1.000000,101.000000,18.000000,0.000000,18.000000,0.000000
25%,12546.750000,2020-12-02 22:21:40.750000128,132.000000,2.000000,1479.000000,31.000000,0.000000,31.000000,0.000000
50%,25018.500000,2021-11-06 04:57:48,254.000000,3.000000,2725.500000,44.000000,0.000000,44.000000,0.000000
75%,37511.000000,2022-10-11 05:45:47.249999872,377.000000,4.000000,3970.250000,57.000000,1.000000,57.000000,0.000000
max,50000.000000,2023-09-15 12:24:08,500.000000,5.000000,5350.000000,70.000000,1.000000,70.000000,1.000000
std,14412.553209,NaN,141.565500,1.414437,1441.540074,15.354491,0.499997,15.354491,0.399568

2.info()-know the data labels

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 202404 entries, 0 to 249999
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Customer ID            202404 non-null  int64
 1   Purchase Date          202404 non-null  datetime64[ns]
 2   Product Category       202404 non-null  object
 3   Product Price          202404 non-null  int64
 4   Quantity               202404 non-null  int64
 5   Total Purchase Amount  202404 non-null  int64
 6   Payment Method         202404 non-null  object
 7   Customer Age           202404 non-null  int64
 8   Returns                202404 non-null  float64
 9   Customer Name          202404 non-null  object
 10  Age                    202404 non-null  int64
 11  Gender                 202404 non-null  object
 12  Churn                  202404 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(7), object(4)
memory usage: 21.6+ MB

3.Calculate total revenue

In [ ]:
df=data['Returns']=data['Product Price']*data['Quantity']

In [ ]:
print(df)

0           36
1         1872
2          576
3          196
4          449
          ...
249995     558
249996      27
249997      85
249998     796
249999    1700
Length: 202404, dtype: int64

4.Most Purchased Products

In [ ]:
top_products=data.groupby('Product Category')["Quantity"].sum().sort_values(ascending=False)
print(top_products)

Product Category
Clothing       182510
Books          181311
Electronics    122104
Home           121139
Name: Quantity, dtype: int64

5.Group customers based on spending.

In [ ]:
cus_spending=data.groupby('Customer ID')['Returns'].sum()

In [ ]:
print(cus_spending)

Customer ID
1         845
2         678
3        4591
4         276
5        3976
         ...
49996    2955
49997    7480
49998     980
49999     360
50000    1383
Name: Returns, Length: 49139, dtype: int64

segments

In [ ]:
segments=pd.qcut(cus_spending,q=3,labels=['Low','Medium','High'])

In [ ]:

print(segments)

Customer ID
1           Low
2           Low
3          High
4           Low
5          High
          ...
49996    Medium
49997      High
49998       Low
49999       Low
50000       Low
Name: Returns, Length: 49139, dtype: category
Categories (3, object): ['Low' < 'Medium' < 'High']

Average Order Value (AOV)

In [ ]:
total=data['Returns'].sum()
total_orders=data['Customer ID'].nunique()
AOV=total/total_orders
print("avg order value=",AOV)

avg order value= 3141.6759396813122

Repeat Customer Analysis

In [ ]:
repeat_cus=data.groupby('Customer ID')['Order ID'].nunique()
repeat=repeat_cus[repeat_cus > 1]
print(repeat)

KeyError: 'Column not found: Order ID'